"""The Alembic chain actually applies, on a real, empty database.

The rest of the suite builds its schema with ``metadata.create_all`` and never runs
Alembic, so nothing else here would notice a migration that cannot run — and a broken
one only shows up on a fresh production database, which is the worst place to find out.

Each test provisions a throwaway database on the same server the test container already
provides, so this costs a `CREATE DATABASE` rather than a container.
"""

import asyncio
import os
from pathlib import Path
from uuid import uuid4

import asyncpg
import pytest

from app.database import make_async_url, make_asyncpg_dsn

ROOT = Path(__file__).resolve().parents[1]


def _dsn(database: str | None = None) -> str:
    dsn = make_asyncpg_dsn(os.environ["DATABASE_URL"])
    if database is None:
        return dsn
    base, _, _ = dsn.rpartition("/")
    return f"{base}/{database}"


@pytest.fixture
async def empty_database():
    """A fresh database, dropped afterwards."""
    name = f"migration_check_{uuid4().hex[:12]}"
    admin = await asyncpg.connect(_dsn())
    try:
        await admin.execute(f'CREATE DATABASE "{name}"')
    finally:
        await admin.close()
    try:
        yield name
    finally:
        admin = await asyncpg.connect(_dsn())
        try:
            await admin.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
        finally:
            await admin.close()


def _run_alembic(command_name: str, database: str, revision: str = "head") -> None:
    """Run an Alembic command against ``database`` in a worker thread.

    Alembic's async ``env.py`` calls ``asyncio.run``, which cannot be invoked from a
    running loop — the same reason ``run_migrations`` uses ``asyncio.to_thread``. The URL
    is set on the config rather than the environment: ``settings`` is bound at import and
    would otherwise send these migrations at the suite's own database.
    """
    from alembic.config import Config

    from alembic import command

    config = Config(str(ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(ROOT / "alembic"))
    # The async driver explicitly: env.py only normalises the URL it derives itself.
    config.set_main_option("sqlalchemy.url", make_async_url(_dsn(database)))
    if command_name == "upgrade":
        command.upgrade(config, revision)
    elif command_name == "downgrade":
        command.downgrade(config, revision)
    else:
        getattr(command, command_name)(config)


async def test_the_chain_applies_to_an_empty_database(empty_database):
    """Every revision, in order, on nothing — what a first deploy does."""
    await asyncio.to_thread(_run_alembic, "upgrade", empty_database)

    connection = await asyncpg.connect(_dsn(empty_database))
    try:
        tables = {
            row["tablename"]
            for row in await connection.fetch(
                "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
            )
        }
    finally:
        await connection.close()

    # A domain table, the queue's, and the limiter's: one from each of the three
    # sources that now contribute schema.
    assert "exercise" in tables
    assert "procrastinate_jobs" in tables
    assert "rate_limit_hits" in tables


async def test_the_migrated_schema_matches_the_models(empty_database):
    """``alembic check`` is the only drift detector this project has, since the test
    suite builds its schema from the models rather than from migrations.

    It also pins the ``include_name`` filter: procrastinate's tables are installed
    verbatim by their own revision and are deliberately absent from SQLModel's metadata,
    so without the filter this would report them as removals on a correct database.
    """
    await asyncio.to_thread(_run_alembic, "upgrade", empty_database)

    await asyncio.to_thread(_run_alembic, "check", empty_database)


async def test_the_rate_limit_table_is_unlogged(empty_database):
    """UNLOGGED is the reason a write per login attempt is acceptable — these rows stay
    out of the WAL. An autogenerated replacement would silently make it a normal table."""
    await asyncio.to_thread(_run_alembic, "upgrade", empty_database)

    connection = await asyncpg.connect(_dsn(empty_database))
    try:
        persistence = await connection.fetchval(
            "SELECT relpersistence FROM pg_class WHERE relname = 'rate_limit_hits'"
        )
    finally:
        await connection.close()

    # pg_class.relpersistence is Postgres's internal "char" type, so asyncpg hands it
    # back as bytes rather than str.
    assert persistence == b"u"


async def test_launch_snapshot_migration_preserves_legacy_uncertainty(empty_database):
    """A legacy active run remains unknown; only an unlaunched draft is authoritative."""
    await asyncio.to_thread(_run_alembic, "upgrade", empty_database, "d8e9f0a1b2c3")
    connection = await asyncpg.connect(_dsn(empty_database))
    try:
        owner_id = await connection.fetchval(
            """
            INSERT INTO "user" (
                email, display_name, hashed_password, role, team, is_active,
                created_at, is_admin, must_change_password, auth_provider,
                subject, auth_tenant, role_managed_by_idp
            ) VALUES (
                'legacy-owner@example.test', 'Legacy Owner', NULL,
                'facilitator'::userrole, NULL, true, now(), false, false,
                'local', NULL, NULL, false
            ) RETURNING id
            """
        )
        scenario_id = await connection.fetchval(
            """
            INSERT INTO scenario (
                title, description, version, tags, definition,
                created_by, created_at, updated_at
            ) VALUES (
                'Legacy', NULL, '1.0', NULL, '{"title":"Legacy","injects":[]}',
                $1, now(), now()
            ) RETURNING id
            """,
            owner_id,
        )

        async def exercise(state: str, title: str) -> int:
            return await connection.fetchval(
                """
                INSERT INTO exercise (
                    scenario_id, title, state, current_node_id, llm_enabled,
                    debrief_notes, started_at, ended_at, paused_at,
                    accumulated_pause_seconds, created_by, created_at
                ) VALUES (
                    $1, $2, $3::exercisestate, NULL, false,
                    NULL, CASE WHEN $3 = 'draft' THEN NULL ELSE now() END,
                    NULL, NULL, 0, $4, now()
                ) RETURNING id
                """,
                scenario_id,
                title,
                state,
                owner_id,
            )

        active_id = await exercise("active", "Legacy active")
        draft_id = await exercise("draft", "Legacy draft")
        for exercise_id in (active_id, draft_id):
            await connection.execute(
                """
                INSERT INTO inject (
                    exercise_id, scenario_node_id, title, content, target_teams,
                    group_id, sequence_order, release_offset_minutes, state,
                    released_at, released_by, resolved_at, resolved_by,
                    resolution_reason, attachment_filename,
                    attachment_content_type, attachment_path, attachment_size
                ) VALUES (
                    $1, 'start', 'Start', 'Respond', NULL, NULL, 0, NULL,
                    'pending'::injectstate, NULL, NULL, NULL, NULL, NULL,
                    NULL, NULL, NULL, NULL
                )
                """,
                exercise_id,
            )
            await connection.execute(
                """
                INSERT INTO exercisemember (
                    exercise_id, user_id, group_id, role_at_enrolment, joined_at
                ) VALUES ($1, $2, NULL, 'facilitator'::userrole, now())
                """,
                exercise_id,
                owner_id,
            )
            await connection.execute(
                """
                INSERT INTO communication (
                    exercise_id, sender_id, sender_team, direction,
                    external_entity, subject, body, triggered_by_inject_id,
                    trigger_key, visible_to_teams, sent_at
                ) VALUES (
                    $1, $2, NULL, 'inbound'::commdirection,
                    'NCSC', 'Legacy', 'Unknown timing', NULL, NULL, NULL, now()
                )
                """,
                exercise_id,
                owner_id,
            )
    finally:
        await connection.close()

    await asyncio.to_thread(_run_alembic, "upgrade", empty_database)
    # A repeated startup migration is a no-op, not a duplicate type/trigger failure.
    await asyncio.to_thread(_run_alembic, "upgrade", empty_database)

    connection = await asyncpg.connect(_dsn(empty_database))
    try:
        exercises = {
            row["title"]: row
            for row in await connection.fetch(
                """
                SELECT title, launch_provenance::text AS provenance,
                       launch_snapshot_digest
                FROM exercise
                """
            )
        }
        assert exercises["Legacy active"]["provenance"] == "unknown"
        assert exercises["Legacy draft"]["provenance"] == "pending"
        assert all(row["launch_snapshot_digest"] is None for row in exercises.values())
        assert await connection.fetchval("SELECT count(*) FROM exercise_launch_snapshot") == 0

        with pytest.raises(asyncpg.CheckViolationError):
            await connection.execute(
                """
                UPDATE exercise
                SET launch_provenance = 'exact'::snapshotprovenance
                WHERE id = $1
                """,
                draft_id,
            )

        for table_name in ("inject", "communication", "exercisemember"):
            origins = {
                row["title"]: row["created_during_run"]
                for row in await connection.fetch(
                    f"""
                    SELECT exercise.title, child.created_during_run
                    FROM {table_name} AS child
                    JOIN exercise ON exercise.id = child.exercise_id
                    """
                )
            }
            assert origins == {"Legacy active": None, "Legacy draft": False}

        # A previous-version replica knows only the lifecycle state. After the schema
        # migration its draft -> active write must fail closed rather than create a new
        # run with pending provenance and no snapshot.
        with pytest.raises(asyncpg.RaiseError, match="provenance is inconsistent"):
            await connection.execute(
                """
                UPDATE exercise
                SET state = 'active'::exercisestate, started_at = now()
                WHERE id = $1
                """,
                draft_id,
            )
        assert (
            await connection.fetchval(
                "SELECT state::text FROM exercise WHERE id = $1", draft_id
            )
            == "draft"
        )

        # Child writes omitted by an old replica are classified while holding the
        # parent row: a post-migration write into a running legacy exercise is known
        # runtime data, not fabricated launch configuration.
        classified_origin = await connection.fetchval(
            """
            INSERT INTO communication (
                exercise_id, sender_id, sender_team, direction,
                external_entity, subject, body, triggered_by_inject_id,
                trigger_key, visible_to_teams, sent_at
            ) VALUES (
                $1, $2, NULL, 'inbound'::commdirection,
                'NCSC', 'Post-migration', 'Created after upgrade',
                NULL, NULL, NULL, now()
            )
            RETURNING created_during_run
            """,
            active_id,
            owner_id,
        )
        assert classified_origin is True

        digest = "a" * 64
        await connection.execute(
            """
            INSERT INTO exercise_launch_snapshot
                (digest, schema_version, content, created_at)
            VALUES (
                $1,
                '1.0',
                '{"exercise":{"title":"Legacy draft","llm_enabled":false}}'::jsonb,
                now()
            )
            """,
            digest,
        )

        # The new application can atomically link a matching snapshot and cross the
        # boundary. Thereafter old replicas cannot rewrite any frozen projection.
        await connection.execute(
            """
            UPDATE exercise
            SET state = 'active'::exercisestate,
                started_at = now(),
                launch_provenance = 'exact'::snapshotprovenance,
                launch_snapshot_digest = $2
            WHERE id = $1
            """,
            draft_id,
            digest,
        )
        with pytest.raises(asyncpg.RaiseError, match="launch settings are immutable"):
            await connection.execute(
                "UPDATE exercise SET title = 'Drifted' WHERE id = $1",
                draft_id,
            )
        with pytest.raises(asyncpg.RaiseError, match="launch settings are immutable"):
            await connection.execute(
                "UPDATE exercise SET scenario_id = $2 WHERE id = $1",
                draft_id,
                scenario_id + 1,
            )
        with pytest.raises(asyncpg.RaiseError, match="inject fields are immutable"):
            await connection.execute(
                """
                UPDATE inject
                SET release_offset_minutes = 99
                WHERE exercise_id = $1
                """,
                draft_id,
            )
        with pytest.raises(asyncpg.RaiseError, match="inject fields are immutable"):
            await connection.execute(
                "DELETE FROM inject WHERE exercise_id = $1",
                draft_id,
            )
        with pytest.raises(asyncpg.RaiseError, match="communications are immutable"):
            await connection.execute(
                """
                UPDATE communication
                SET subject = 'Drifted'
                WHERE exercise_id = $1
                """,
                draft_id,
            )
        with pytest.raises(asyncpg.RaiseError, match="communications are immutable"):
            await connection.execute(
                "DELETE FROM communication WHERE exercise_id = $1",
                draft_id,
            )

        runtime_inject_id, runtime_origin = await connection.fetchrow(
            """
            INSERT INTO inject (
                exercise_id, scenario_node_id, title, content, target_teams,
                group_id, sequence_order, release_offset_minutes, state,
                released_at, released_by, resolved_at, resolved_by,
                resolution_reason, attachment_filename,
                attachment_content_type, attachment_path, attachment_size,
                attachment_sha256
            ) VALUES (
                $1, NULL, 'Runtime', 'Allowed', NULL, NULL, 10, NULL,
                'pending'::injectstate, NULL, NULL, NULL, NULL, NULL,
                NULL, NULL, NULL, NULL, NULL
            )
            RETURNING id, created_during_run
            """,
            draft_id,
        )
        assert runtime_origin is True
        await connection.execute(
            "UPDATE inject SET title = 'Runtime edited' WHERE id = $1",
            runtime_inject_id,
        )

        with pytest.raises(asyncpg.RaiseError, match="snapshots are immutable"):
            async with connection.transaction():
                await connection.execute(
                    "UPDATE exercise_launch_snapshot "
                    "SET content = '{\"changed\":true}' WHERE digest = $1",
                    digest,
                )
    finally:
        await connection.close()
