apiVersion: v1
kind: Service
metadata:
  name: deep-thought-app
  namespace: deep-thought
  labels:
    app.kubernetes.io/name: deep-thought-app
    app.kubernetes.io/part-of: deep-thought
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: deep-thought-app
  ports:
    - port: 8000
      targetPort: 8000
      name: http
