# pyright: reportArgumentType=false
# SQLModel's Field stub is narrower than its runtime SQLAlchemy type support.
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import DateTime
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from app.models.exercise import Exercise


class ExecutiveSummary(SQLModel, table=True):
    """LLM-drafted executive summary for an exercise's after-action report (#113).

    One-to-one with an exercise. Draft text is generated by the pluggable provider
    layer as a background task and is editable by the facilitator before it lands in
    the report — ``edited`` records that a human has revised the machine draft.
    """

    id: int | None = Field(default=None, primary_key=True)
    exercise_id: int = Field(foreign_key="exercise.id", ondelete="CASCADE", unique=True)
    summary_text: str
    llm_model: str  # provider.llm_model_label at generation time
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC), sa_type=DateTime(timezone=True)
    )
    edited: bool = Field(default=False)

    exercise: Optional["Exercise"] = Relationship(back_populates="executive_summary")
